### ISSUE TITLE
Installation of Dip fails when building Clp

### ISSUE THREAD

**Issue by fontanf** [coin-or/coinbrew#11]
I tried to install Dip with coinbrew as mentioned here https://github.com/coin-or/Dip/blob/master/INSTALL.md

```
git clone https://www.github.com/coin-or/coinbrew
cd coinbrew
./coinbrew fetch build Dip --no-prompt
```

The installation fails when building Clp
```
##################################################
### Building Clp 
##################################################

Making all in src
make[1] : on entre dans le répertoire « /home/fontanf/coinbrew/build/Clp/src »
make  all-am
make[2] : on entre dans le répertoire « /home/fontanf/coinbrew/build/Clp/src »
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo /home/fontanf/coinbrew/Clp/Clp/src`  -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src  -DCOIN_HAS_CLP     -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCLP_BUILD -c -o ClpCholeskyBase.lo /home/fontanf/coinbrew/Clp/Clp/src/ClpCholeskyBase.cpp
mkdir .libs
 g++ -DHAVE_CONFIG_H -I. -I/home/fontanf/coinbrew/Clp/Clp/src -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -c /home/fontanf/coinbrew/Clp/Clp/src/ClpCholeskyBase.cpp  -fPIC -DPIC -o .libs/ClpCholeskyBase.o
In file included from /home/fontanf/coinbrew/Clp/Clp/src/ClpModel.hpp:23:0,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpInterior.hpp:20,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpCholeskyBase.cpp:28:
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:17:14: warning: 'COIN_DBL_MIN' defined but not used [-Wunused-variable]
 const double COIN_DBL_MIN = (std::numeric_limits< double >::min)();
              ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:19:11: warning: 'COIN_INT_MAX' defined but not used [-Wunused-variable]
 const int COIN_INT_MAX = (std::numeric_limits< int >::max)();
           ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:20:14: warning: 'COIN_INT_MAX_AS_DOUBLE' defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = (std::numeric_limits< int >::max)();
              ^
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo /home/fontanf/coinbrew/Clp/Clp/src`  -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src  -DCOIN_HAS_CLP     -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCLP_BUILD -c -o ClpCholeskyDense.lo /home/fontanf/coinbrew/Clp/Clp/src/ClpCholeskyDense.cpp
 g++ -DHAVE_CONFIG_H -I. -I/home/fontanf/coinbrew/Clp/Clp/src -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -c /home/fontanf/coinbrew/Clp/Clp/src/ClpCholeskyDense.cpp  -fPIC -DPIC -o .libs/ClpCholeskyDense.o
In file included from /home/fontanf/coinbrew/Clp/Clp/src/ClpModel.hpp:23:0,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpInterior.hpp:20,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpCholeskyDense.cpp:12:
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:17:14: warning: 'COIN_DBL_MIN' defined but not used [-Wunused-variable]
 const double COIN_DBL_MIN = (std::numeric_limits< double >::min)();
              ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:19:11: warning: 'COIN_INT_MAX' defined but not used [-Wunused-variable]
 const int COIN_INT_MAX = (std::numeric_limits< int >::max)();
           ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:20:14: warning: 'COIN_INT_MAX_AS_DOUBLE' defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = (std::numeric_limits< int >::max)();
              ^
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo /home/fontanf/coinbrew/Clp/Clp/src`  -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src  -DCOIN_HAS_CLP     -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCLP_BUILD -c -o ClpConstraint.lo /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraint.cpp
 g++ -DHAVE_CONFIG_H -I. -I/home/fontanf/coinbrew/Clp/Clp/src -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -c /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraint.cpp  -fPIC -DPIC -o .libs/ClpConstraint.o
In file included from /home/fontanf/coinbrew/Clp/Clp/src/ClpModel.hpp:23:0,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpSimplex.hpp:16,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraint.cpp:7:
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:19:11: warning: 'COIN_INT_MAX' defined but not used [-Wunused-variable]
 const int COIN_INT_MAX = (std::numeric_limits< int >::max)();
           ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:20:14: warning: 'COIN_INT_MAX_AS_DOUBLE' defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = (std::numeric_limits< int >::max)();
              ^
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo /home/fontanf/coinbrew/Clp/Clp/src`  -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src  -DCOIN_HAS_CLP     -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCLP_BUILD -c -o ClpConstraintLinear.lo /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraintLinear.cpp
 g++ -DHAVE_CONFIG_H -I. -I/home/fontanf/coinbrew/Clp/Clp/src -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -c /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraintLinear.cpp  -fPIC -DPIC -o .libs/ClpConstraintLinear.o
In file included from /home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinIndexedVector.hpp:15:0,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraintLinear.cpp:8:
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:19:11: warning: 'COIN_INT_MAX' defined but not used [-Wunused-variable]
 const int COIN_INT_MAX = (std::numeric_limits< int >::max)();
           ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:20:14: warning: 'COIN_INT_MAX_AS_DOUBLE' defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = (std::numeric_limits< int >::max)();
              ^
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo /home/fontanf/coinbrew/Clp/Clp/src`  -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src  -DCOIN_HAS_CLP     -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCLP_BUILD -c -o ClpConstraintQuadratic.lo /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraintQuadratic.cpp
 g++ -DHAVE_CONFIG_H -I. -I/home/fontanf/coinbrew/Clp/Clp/src -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -c /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraintQuadratic.cpp  -fPIC -DPIC -o .libs/ClpConstraintQuadratic.o
In file included from /home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinIndexedVector.hpp:15:0,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpConstraintQuadratic.cpp:8:
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:19:11: warning: 'COIN_INT_MAX' defined but not used [-Wunused-variable]
 const int COIN_INT_MAX = (std::numeric_limits< int >::max)();
           ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:20:14: warning: 'COIN_INT_MAX_AS_DOUBLE' defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = (std::numeric_limits< int >::max)();
              ^
/bin/bash ../libtool --tag=CXX --mode=compile g++ -DHAVE_CONFIG_H -I. -I`echo /home/fontanf/coinbrew/Clp/Clp/src`  -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src  -DCOIN_HAS_CLP     -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long   -DCLP_BUILD -c -o Clp_C_Interface.lo /home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp
 g++ -DHAVE_CONFIG_H -I. -I/home/fontanf/coinbrew/Clp/Clp/src -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -c /home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp  -fPIC -DPIC -o .libs/Clp_C_Interface.o
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp: In function 'const char* Clp_Version()':
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp:198:10: error: 'CLP_VERSION' was not declared in this scope
   return CLP_VERSION;
          ^
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp: In function 'int Clp_VersionMajor()':
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp:203:10: error: 'CLP_VERSION_MAJOR' was not declared in this scope
   return CLP_VERSION_MAJOR;
          ^
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp: In function 'int Clp_VersionMinor()':
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp:207:10: error: 'CLP_VERSION_MINOR' was not declared in this scope
   return CLP_VERSION_MINOR;
          ^
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp: In function 'int Clp_VersionRelease()':
/home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp:211:10: error: 'CLP_VERSION_RELEASE' was not declared in this scope
   return CLP_VERSION_RELEASE;
          ^
In file included from /home/fontanf/coinbrew/Clp/Clp/src/ClpModel.hpp:23:0,
                 from /home/fontanf/coinbrew/Clp/Clp/src/ClpSimplex.hpp:16,
                 from /home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp:13:
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp: At global scope:
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:19:11: warning: 'COIN_INT_MAX' defined but not used [-Wunused-variable]
 const int COIN_INT_MAX = (std::numeric_limits< int >::max)();
           ^
/home/fontanf/coinbrew/CoinUtils/CoinUtils/src/CoinFinite.hpp:20:14: warning: 'COIN_INT_MAX_AS_DOUBLE' defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = (std::numeric_limits< int >::max)();
              ^
Makefile:961 : la recette pour la cible « Clp_C_Interface.lo » a échouée
make[2]: *** [Clp_C_Interface.lo] Erreur 1
make[2] : on quitte le répertoire « /home/fontanf/coinbrew/build/Clp/src »
Makefile:713 : la recette pour la cible « all » a échouée
make[1]: *** [all] Erreur 2
make[1] : on quitte le répertoire « /home/fontanf/coinbrew/build/Clp/src »
Makefile:519 : la recette pour la cible « all-recursive » a échouée
make: *** [all-recursive] Erreur 1
```

Ubuntu 16.04.6 LTS
gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.11) 

Any thoughts?

Florian

**Comment by svigerske** [comment]
We had seen this somewhere else, but couldn't reproduce this.
The compile call has
```
g++ -DHAVE_CONFIG_H 
 -I. 
 -I/home/fontanf/coinbrew/Clp/Clp/src
 -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src 
 -I/home/fontanf/coinbrew/build/CoinUtils/src
 -DCOIN_HAS_CLP  -DCLP_BUILD
```
and is executed in `/home/fontanf/coinbrew/build/Clp/src`.
So `Clp_C_Interface.c` should include `/home/fontanf/coinbrew/Clp/Clp/src/ClpConfig.h`, which should then include `/home/fontanf/coinbrew/build/Clp/src/config.h`, which should define `CLP_VERSION`, etc.
I don't really see why this does not happen. If you could figure that out, that would be helpful.

`Clp_C_Interface.c` has an include of `CoinUtilsConfig.h` in the beginning, which it should take from `/home/fontanf/coinbrew/CoinUtils/CoinUtils/src`, which should include `/home/fontanf/coinbrew/build/CoinUtils/src/config_coinutils.h`. I was fearing that this could lead to some confusion, but I don't see how.

**Comment by fontanf** [comment]
Thanks for the quick reply!

I manually added the definition of `CLP_VERSION_RELEASE` at the end of `./build/CoinUtils/src/config.h`
```
#define CLP_VERSION_RELEASE 9999
```

And the corresponding error disappeared. It seams that `./build/CoinUtils/src/config.h` is included instead of `./build/Clp/src/config.h`

**Comment by svigerske** [comment]
Ah yes, that should be it.

The `-I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src` in the compiler flags is actually too much. The Clp build should not use the CoinUtils source tree, but build against an installed version of CoinUtils.

**Comment by tkralphs** [comment]
Hmm, as with the last time this was reported, I cannot reproduce this. I built from a clean checkout and everything went through without problems, so there is something deeper going on here. I don't think what @svigerske is pointing out is not really the issue. Yes, it's true that we should be building against installed versions (I thought this was already happening---I have to look into this), but this is not the issue. The missing symbols are defined by Clp itself and when building Clp, we _do_ use the uninstalled headers in `coinbrew/Clp/Clp/src` (with the exception of `config.h`, which is produced by the `configure` script and is pulled from `coinbrew/build/Clp/src`).

When I build, I get the exact same compilation command, yet everything works. `Clp_C_interface.cpp` includes `ClpConfig.h` from `coinbrew/Clp/Clp/src`, which pulls in `config.h` from the `build/Clp/src` (due to the `-I.` in the compilation command and the fact that `CLP_BUILD` is defined). The Clp version symbols are defined in `config.h`, as expected. 

@fontanf Can you check where this breaks down for you? Is there a `config.h` in `build/Clp/src` and does it define the missing symbols? If so, I don't see how it can be failing. If not, we need to find out why not. We still haven't gotten to the root of the issue and I would really appreciate it if you would do a little more digging. I've been unable to reproduce this myself so far and this is the second report we've received.

**Comment by svigerske** [comment]
He also has ` -I/home/fontanf/coinbrew/build/CoinUtils/src` and there should be the `config.h` from CoinUtils in that directory. Maybe it depends on compiler versions or other things whether config.h is picked up from `coinbrew/build/Clp/src` or `coinbrew/build/CoinUtils/src`. I don't know how this worked reliably in the past, though.

**Comment by tkralphs** [comment]
OK, so it seems that it is the case that `pkg-config` in fact prefers the `-uninstalled.pc` files over the `.pc` files. There is an environment variable `PKG_CONFIG_DISABLE_UNINSTALLED` that is needed to disable this behavior. However, I think the correct thing to do is just not to include the source directories in `PKG_CONFIG_PATH` unless we intend to use the uninstalled versions for some reason. This will require a little rejiggering in `coin.m4`. I'll try to get to this later unless @svigerske beats me to it.

**Comment by svigerske** [comment]
If Clp is configured against the uninstalled version of CoinUtils, then pkg-config will pick up the `coinutils-uninstalled.pc` file (unless called with `--no-uninstalled` or `PKG_CONFIG_DISABLE_UNINSTALLED` set) and so you get include paths pointing into the CoinUtils source tree. That seems to be correct to me.

I agree with "In any case, the real fix is to ensure we are building against installed versions." Then you will not have to worry about `coinutils-uninstalled.pc` being picked up.
Who is including source directories in `PKG_CONFIG_PATH`?

**Comment by tkralphs** [comment]
The way `configure` script is being called, the clear intention and expectation is be that we are  _not_ configuring against the uninstalled version. The only path given is to the installed version (using `--with-coininstdir). It only finds the uninstalled version at all because it happens by chance to be in the "default" location (`../../`). The logic of this "default" location in `coin.m4` is mainly there because of the fallback mechanism that we left in place for when `pkg-config` is not present and no locations for the required packages is specified (to allow the old style monolithic build to keep working without `pkg-config`). The "default" location should **not** be checked when `pkg-config` is present, however, except perhaps in the case where the `.pc` files can't otherwise be located in the existing `PKG_CONFIG_PATH`.

The path to the `-uninstalled.pc` files gets added on line 3483 of `coin.m4`:
```
    PKG_CONFIG_PATH="$COIN_PKG_CONFIG_PATH:$COIN_PKG_CONFIG_PATH_UNINSTALLED"
```
Since the installed directories are listed first, this would still not be a problem except for the preference of pkg-config for the `-uninstalled.pc` files. We should only add the "default" path to the uninstalled files when there is no `.pc` file found in the installed path.

And actually, we should also be checking the user's pre-set path as well. If I installed CoinUtils somewhere and then just add that directory to my own `PKG_CONFIG_PATH` external to `configure`, this should also work, i.e, I should not need to actually use `--with-coininstdir` in this case). Currently, however, we set aside the user's path and restore it afterwards. This seems incorrect.

**Comment by svigerske** [comment]
Ah yes, the `../../` lookup. Thanks.
Indeed, the monolithic builds require this, but they should also use pkg-config in any case, if available, and not rely on the fallback.

I would suggest to skip adding `COIN_PKG_CONFIG_PATH_UNINSTALLED` to `PKG_CONFIG_PATH` if `PKG_CONFIG_DISABLE_UNINSTALLED` is set and set the latter in the coinbrew script.
Probably setting `PKG_CONFIG_DISABLE_UNINSTALLED` would already be sufficient.
With the next BuildTools, all this `-uninstalled.pc` files will go away anyway.

`COIN_PKG_CONFIG_PATH` includes the original `PKG_CONFIG_PATH`, so the user's one is checked first.

**Comment by tkralphs** [comment]
I don't think it's true that the `COIN_PKG_CONFIG_PATH` includes the user's existing path. The line quoted above completely replaces the existing path. It is stored in a temporary variable and then restored later. Am I missing something? 

I'm not sure if setting `PKG_CONFIG_DISABLE_UNINSTALLED` in `coinbrew` is the right solution. This seems a "bug" in BuildTools and the behavior observed would then still happen if installing packages by hand. When calling the package `configure` directly, it is unexpected behavior that `configure` would even see the uninstalled version when not doing a monolithic build. I'm not sure why one would add  `COIN_PKG_CONFIG_PATH_UNINSTALLED` to `PKG_CONFIG_PATH` when not calling the fallback function for finding packages. I guess the only case in which we would want to detect the `-uninstalled.pc` files is when doing a monolithic build. We can just detect whether we are doing a monolithic build? Maybe we could check whether the `.pc` file is found somewhere other than in the project's build directory?

Of course, all this will be moot once we finish the new version of BuildTools, so maybe a clunky workaround is OK for now.

**Comment by svigerske** [comment]
I was looking into line 3043, where the assembly of COIN_PKG_CONFIG_PATH is starting:
```
# assemble pkg-config search path for installed projects
COIN_PKG_CONFIG_PATH="$PKG_CONFIG_PATH"
```

That we look into `../../` was added to make the monolithic builds easy. I don't know another easy way to have the monolithic builds work. And I don't like the fallback much. It is incomplete (completely ignores restrictions on package versions) and fragile.

So, one could add something to coin.m4 to not make it look into `../../` under some circumstances. I think you suggest to first look for packages without having `../../` in the PKG_CONFIG_PATH, and then repeat with the monolithic-build-enabled one if the package isn't found. That introduces the danger that in a monolithic build we may use a mix of packages somewhere installed in system and those that we are just building.
Or, as you say, one could try to recognize whether a monolithic build is happening. How to do this? Would the top level configure have to find a way to pass this on to all the configures in the subdirectories? What if one reconfigures only one package, will it still know that we were in a monolithic build.
Thus, an "elegant" workaround in coinbrew is my perferred choice :).

**Comment by fontanf** [comment]
> @fontanf Can you check where this breaks down for you? Is there a `config.h` in `build/Clp/src` and does it define the missing symbols? If so, I don't see how it can be failing. If not, we need to find out why not. We still haven't gotten to the root of the issue and I would really appreciate it if you would do a little more digging. I've been unable to reproduce this myself so far and this is the second report we've received.

`build/Clp/src/config.h` is present and defines the missing variables. When I add option `-H` to the `g++` command, I get:
```
. /home/fontanf/coinbrew/Clp/Clp/src/ClpConfig.h
.. /home/fontanf/coinbrew/build/CoinUtils/src/config.h
```
which confirms that the wrong `config.h` is included. However, I really don't understand why since `-I.` is placed before `-I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src` in the `g++` command

**Comment by fontanf** [comment]
An other strange observation. I changed relative paths `-I.` and `.libs/Clp_C_Interface.o` to absolute path in the `g++` command:
```
g++ -DHAVE_CONFIG_H -I/home/fontanf/coinbrew/build/Clp/src/ -I/home/fontanf/coinbrew/Clp/Clp/src -I/home/fontanf/coinbrew/CoinUtils/CoinUtils/src -I/home/fontanf/coinbrew/build/CoinUtils/src -DCOIN_HAS_CLP -O3 -pipe -DNDEBUG -Wparentheses -Wreturn-type -Wcast-qual -Wall -Wpointer-arith -Wwrite-strings -Wconversion -Wno-unknown-pragmas -Wno-long-long -DCLP_BUILD -c /home/fontanf/coinbrew/Clp/Clp/src/Clp_C_Interface.cpp  -fPIC -DPIC -o /home/fontanf/coinbrew/build/Clp/src/.libs/Clp_C_Interface.o
```

The same errors appear if I compile from `build/Clp/src`. However, if I compile from any other directory, the errors disappear

**Comment by fontanf** [comment]
I eventually managed to find where the issue came from. It seems that `g++` doesn't like when the environment variable `CPLUS_INCLUDE_PATH` starts with a colon... I don't know why but just adding `export CPLUS_INCLUDE_PATH="/home"` at the beginning of my `.bashrc` solved the issue

Sorry for the inconvenience and thanks for the help!

**Comment by tkralphs** [comment]
@fontaf No worries, this was actually a good exercise to see how everything is currently working and we uncovered one important issue for our use of `pkg-config`. It's good to know how this problem we had seen before can actually arise in the wild.

@svigerske OK, now I see that the user's `PKG_CONFIG_PATH` is actually incorporated. Also, I agree that there really isn't much of a good way to fix the issue while allowing monolithic builds to work. Once we move over to git fully, I don't think we need to support monolithic builds any longer, though. For now, I will just disable detection of uninstalled packages in `coinbrew`.
