### ISSUE TITLE
CoinBazaar (as a dependency of OS)

### ISSUE THREAD

**Issue by karkhaneei** [coin-or/coinbrew#12]
It seems that ApplicationTemplates is a dependency of OS. But, there is no such repository in Github (also GitHub has not CoinBazaar repository).

**Comment by tkralphs** [comment]
Sorry for this, the script should know to get those from SVN. There is a COIN-OR Bazaar organization (https://github.com/coin-or-bazaar), which will be the home for application templates. We just need to do the mirroring to move it over and there are some technical issues to be resolved in the case of the old CoinBazaar project. Please stay tuned. In the meantime, if you just remove that line from the Dependencies file, it should work fine. If you want you can check out application templates manually for now. Please stay tuned!

**Comment by karkhaneei** [comment]
Thanks, for your response.

Removing the corresponding line from the Dependencies file works fine.

Best regards

**Comment by tkralphs** [comment]
This is now fixed.
