### ISSUE TITLE
Bad path substitution for ThirdParty/ASL

### ISSUE THREAD

**Issue by ikus060** [coin-or/coinbrew#17]
When executing: ```
root@eee36a126dfc:/build#  ./coinbrew fetch https://github.com/ikus060/Cbc --no-prompt --no-third-party
```
I have this error.
```
##################################################
##################################################

./coinbrew: line 1016: cd: /build/build/ThirdParty/ASL: No such file or directory
root@eee36a126dfc:/build# ls
BuildTools  Cbc  ThirdParty  coinbrew
```

**Comment by ikus060** [comment]
I see two changes made after 42bc4dd, I suspect one of these introduce the defect cause 42bc4dd is working well.

**Comment by tkralphs** [comment]
Ack, that was stupid. I guess that `coinbrew` will become pretty stable soon, but I was already thinking that some automated testing would be good. Maybe we can throw together a .travis.yml that tests the usual cases just to make sure I don't do anything stupid like that.
