### ISSUE TITLE
repository 'https://github.com/coin-or/CHiPPS/Bcps/' not found

### ISSUE THREAD

**Issue by pgirardgerad** [coin-or/coinbrew#19]
Running coinbrew with the menu and trying to download 13 (biceps), there's an error message about git and then later an error about the repository not found.

13. BiCePS
 14. Blis
 15. Dip
 16. Bonmin
 17. Couenne
 18. Optimization Services
 19. MibS
 20. DisCO
 21. All
 22. Let me enter another project
=> 13

./coinbrew: line 449: [git: command not found

##################################################
##################################################

Cloning into 'CHiPPS/Bcps'...
fatal: repository 'https://github.com/coin-or/CHiPPS/Bcps/' not found
 $ ▶ which git
/usr/bin/git

From the COIN-OR-OptimizationSuite/Dependencies, the link is different.
Bcps              https://github.com/coin-or/CHiPPS-BiCePS master

**Comment by pgirardgerad** [comment]
I don't know if it's something specific to my bash version but it seems the problem was caused by a lack of a space after the "[" in the VCS test.

There's a few other packages that would be affected as well. Here's what I did and it seems to work.

```
diff --git a/coinbrew b/coinbrew
index 7e52318..cc82e44 100755
--- a/coinbrew
+++ b/coinbrew
@@ -431,7 +431,7 @@ function user_prompts {
             3)  main_proj=Cbc;;
             4)  main_proj=DyLP;;
             5)
-                if [$VCS = git ]; then
+                if [ $VCS = git ]; then
                     main_proj=FlopCpp
                 else
                     main_proj=FlopC++
@@ -444,21 +444,21 @@ function user_prompts {
             10)  main_proj=Bcp;;
             11)  main_proj=Ipopt;;
             12)
-                if [$VCS = git ]; then
+                if [ $VCS = git ]; then
                     main_proj=CHiPPS-ALPS
                 else
                     main_proj=CHiPPS/Alps
                 fi
                 ;;
             13)
-                if [$VCS = git ]; then
+                if [ $VCS = git ]; then
                     main_proj=CHiPPS-BiCePS
                 else
                     main_proj=CHiPPS/Bcps
                 fi
                 ;;
             14)
-                if [$VCS = git ]; then
+                if [ $VCS = git ]; then
                     main_proj=CHiPPS-BLIS
                 else
                     main_proj=CHiPPS/Blis

```

**Comment by tkralphs** [comment]
No, it's not your bash version, that is definitely a bug, thanks! I just somehow never tickled that part of the code. It should be fixed now.
