### ISSUE TITLE
HSL and Lapack dependency order?

### ISSUE THREAD

**Issue by eslickj** [coin-or/coinbrew#24]
I'm having some problems using coinbrew with the HSL.  HSL needs Lapack, but I think Thirdparty/Lapack gets built after HSL.  The HSL configure finds BLAS and if I use the system Lapack everything is fine, so I think there is just a problem with the order the dependencies are built.

**Comment by svigerske** [comment]
7fe1bb8 will probably help. I don't really have plans for another release from Ipopt 3.12, as we are at 3.13 since a while now.
