### ISSUE TITLE
fetch cbc from SVN not working

### ISSUE THREAD

**Issue by h-g-s** [coin-or/coinbrew#25]
Trying to fetch cbc from svn gives an error:

[haroldo@nh src]$ ~/bin/coinbrew fetch Cbc --svn
Welcome to the COIN-OR fetch and build utility
For help, run script with --help.
Package will be built in /home/haroldo/src/build
Entering interactive mode (suppress with --no-prompt)...

##################################################
##################################################
svn: E170000: URL 'https://projects.coin-or.org/svn/Cbc/Cbc' não existe

**Comment by tkralphs** [comment]
Fixed via 7116fcf
