### ISSUE TITLE
coinbrew not working at all on my Mac

### ISSUE THREAD

**Issue by frangio68** [coin-or/coinbrew#27]
coinbrew frangio$ ./coinbrew
./coinbrew: line 1147: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]

I tried also running it with "build" and "fetch" options, but to no avail.

I'm running macOS Mojave 10.14.6, just updated to the latest XCode.

I hope this does not mean I have to install Catalina, which I'm resisting to.

I also tried to collate the repositories I need for building FlopCpp, but I can't figure out the exact positioning of the various source trees. Perhaps a hint somewhere about how this can be done manually could be a nice touch for cases where the automatic version fails?

**Comment by svigerske** [comment]
`declare -A` is bash >= 4 from 2009, [as far as I see](https://www.tldp.org/LDP/abs/html/bashver4.html). If you have an easy way to update your bash, then this may work.

coinbrew just gets and builds the dependencies that are listed in the Dependencies file of the project to be build. For FlopCpp this would be https://github.com/coin-or/FlopCpp/blob/master/Dependencies. So you can just get, build, and install each of them (but skip BuildTools) one-by-one, always using the same `--prefix`.

**Comment by tkralphs** [comment]
This is a well-known problem on OS X. Apple refuses to update to a recent bash. Just install bash from homebrew as noted [here](https://coin-or.github.io/user_introduction.html#os-x-1) and everything will be peachy. This should be done anyway, independent of `coinbrew`.

**Comment by frangio68** [comment]
Indeed, I turned out having a bash 3.x from 2007. A simple brew install bash fixed it for me. Thanks.

Does "always using the same --prefix" still assumes using coinbrew?. If so, it may still not be 100% clear to me how to do that manually using git, if for some reason I were unable to use it. It is always nice to have a fallback option. But, of course, when the automatic system works, it is better.

**Comment by tkralphs** [comment]
We're in a (perpetual) state of transition to full management using git (currently still just mirroring to git in many cases), but I'm working on some updated documentation for the "new" world of working with git repos. 

In a nutshell, you can clone the repo for the project you want to build and then look at the `Dependencies` file to find out which other repos you need (this file may be in the `.coin-or` sub-drectory). If you clone all repos in the `Dependencies` file and check out the indicated branch, then you should be able to build them one by one, installing to a common prefix using the standard 
```
configure
make
make install
```
It shouldn't be too difficult to do this manually once, but `coinbrew` gives you a lot of nice bells and whistles like being able to update all dependencies easily, re-building everything with a single command, working with multiple version and multiple projects within the same source tree, etc.

**Comment by tkralphs** [comment]
I wasn't quite sure what you meant about whether "always using the same --prefix" still assumes using coinbrew. Could you clarify?

By the way. on OSX, there are [homebrew recipes](https://github.com/coin-or-tools/homebrew-coinor) for the Cbc stack and I intend to eventually add recipes for all the project in the optimization suite. I can try to work one up for FlopC++ if it would be useful. You can just do
```
brew tap coin-or-tools/coinor
brew install cbc
```
That's the easieast way to build on OS X.

**Comment by frangio68** [comment]
The main issues for which I typically need to compile from source is:

- building FlopC++ fails on clang++ (I just tested it, it still happens), one has to force use of g++
- I want OsiCpx built in

As for less serious issues, I favor static libraries over dynamic ones, and I often have problems convincing compressed input to work, so I disable it. But these I could learn to live with.

I was assuming --prefix was a coinbrew option, but checking it I realized it was already a configure option. So forget about my remark there. I fully agree that when the automatic option works, it is much better.

We are doing a largish project with a significant number of sub-projects, and our take so far has been to have an "umbrella" repository with all the sub-projects as sub-repositories. In this way, the whole project can be fetched with a simple

git clone --recursive

But of course you need something better if you want to be able to select only a subset of the stuff and the right dependencies thereof. We have been thinking about using a package manager like Conan, but it does not seem it really does what we want. Our expert friends have decreed that there is really not something that does it, so we would have to build it, but we don't have the time now (and it's unclear if we ever will).

**Comment by tkralphs** [comment]
I feel your pain, I've spent the last fgew years slowly building up `coinbrew` as a sort of package manager for the COIN-OR stuff and it's now pretty full-featured. I didn't look that hard for an alternative, but I didn't really find anything out there that did what I needed, as you say. homebrew and linuxbrew are actually pretty close, but linuxbrew doesn't play that well with Linux distributions in general, as it is trying to be its own Linux distribution in essence (which is actually kind of the point). 

At this point, coinbrew is pretty close to being a general package manager of sorts. Not much of it is specific to COIN. If you just stick a `Dependencies` file into a git repo. it will clone all the dependencies and build then in order. The stuff that is COIN-specific is stuff that assumes the branches and tags are named in certain ways for switching versions, but that could be modified easily. Perhaps there is some scope for generalizing this to be a tool you could also use. 

In any case, with respect to COIN packages, you can do everything you need, as well as more or less anything at all that you can do manually, through `coinbrew`. You can pass it arbitrary configure options and it passes them through. So to compile with `g++` and `OsiCpx,` you can just do
```
coinbrew fetch build FlopCpp CC=gcc CXX=g++ \
--with-cplex-lib=-L/usr/local/cplex/lib/x86-64_sles10_4.1/static_pic/ -lcplex -lpthread -lm \
--with-cplex-incdir=/usr/local/cplex/include/ilcplex 
```
The configure options get cached and re-applied if the build gets interrupted or you want to re-build or re-configure. You can have multiple build directories with different configure options in each. You can even have multiple projects with mixed versions in the same build directory---the different packages and versions are separated out into subdirectories. So it's pretty full-featured, but not very fully documented yet :).

**Comment by frangio68** [comment]
> At this point, coinbrew is pretty close to being a general package manager of sorts. Not much of it is specific to COIN. If you just stick a Dependencies file into a git repo. it will clone all the dependencies and build then in order. The stuff that is COIN-specific is stuff that assumes the branches and tags are named in certain ways for switching versions, but that could be modified easily. Perhaps there is some scope for generalizing this to be a tool you could also use.

There might indeed be scope for a general version that does stuff that other package managers do not.

Our project aims at being "very granular", and it would be good to be able to even have a sort of "meta-lib", against which all objectives could link without knowing in details what exactly is there, just with the knowledge that whatever they need will be. The point is that we are deeply in the factory game, where some parts of the mathematical problem only knows that some other part is "a Block" but not which exact type it is, and that it will be solved by "an appropriate Solver". The actual types of both will be known at runtime via just strings, but there is no need for compile-time information. It therefore would be possible to have a very general code that takes "any Block" and solves it with "any appropriate Solver". Ideally,  while building it one would not want to specify which specific Block/Solver are actually supported, with the idea that "whatever has been built and is available can be used". This would, as I was saying, require that the code can link against some "central repository/meta library" without having to bother what is actually there inside.

Something like this goes even deeper than a package manager, as it needs to care for the actual form of the produced libraries. To the best of our knowledge there is nothing around that does something like this. But, of course, it would have to have at least the functionalities of coinbrew, so this is clearly a possible starting point. And it requires a very tight integration of everything, which is not what COIN-OR does.

> In any case, with respect to COIN packages, you can do everything you need, as well as more or less anything at all that you can do manually, through coinbrew. You can pass it arbitrary configure options and it passes them through. So to compile with g++ and OsiCpx, you can just do
> 
> coinbrew fetch build FlopCpp CC=gcc CXX=g++ \
> --with-cplex-lib=-L/usr/local/cplex/lib/x86-64_sles10_4.1/static_pic/ -lcplex -lpthread -lm \
> --with-cplex-incdir=/usr/local/cplex/include/ilcplex 

Yes, something like this is indeed what I have done yesterday night. It worked absolutely fine. Thanks.

	A.

**Comment by tkralphs** [comment]
Well, let's keep  in touch and let me know if you would like to think about splitting off `coinbrew` into a more generic project. I could try to split out the functions that are specific to COIN and leave a useful core, not sure exactly what that would look like. In any case, I am VERY interested in knowing more about what you guys are working on, sounds amazing and right up my alley.

**Comment by frangio68** [comment]
> Well, let's keep in touch and let me know if you would like to think about splitting off coinbrew into a more generic project. I could try to split out the functions that are specific to COIN and leave a useful core, not sure exactly what that would look like.

We'll look into it in due time. However, as I said, I think what we really want is something that goes down to the linking phase, hence I'm not sure if coinbrew will make sense.

> In any case, I am VERY interested in knowing more about what you guys are working on, sounds amazing and right up my alley.

I'm glad to hear it. The repos are not public, but they will as soon as I can force myself to make them. Documentation of the "core" of the SMS++ system is already available

	https://smspp.gitlab.io/

but we are working in these hours to extend it so that all currently available modules that use it are also documented in the same place, so those pages should become a lot more interesting soon.

A bunch of presentations that try to give a sense of what we are doing are available here

	https://www.plan4res.eu/results/presentations/

All feedback is extremely welcome.

	Best

	Antonio
