### ISSUE TITLE
coinbrew skips HSL

### ISSUE THREAD

**Issue by iaravena** [coin-or/coinbrew#28]
coinbrew is skipping HSL even when HSL full (e.g. from http://www.hsl.rl.ac.uk/ipopt/) is downloaded and left in `ThirdParty/HSL/coinhsl`, as indicated in [INSTALL.HSL](https://github.com/coin-or-tools/ThirdParty-HSL/blob/master/INSTALL.HSL), i.e.

```
$ /path/to/coinbrew build Ipopt:releases/3.13.0
```
results in
```
...
##################################################
### Skipping ThirdParty/HSL 
##################################################
...
```

Is this expected?
I know I can compile HSL manually and pass the flags `--with-hsl-cflags` and `--with-hsl-lflags` to `coinbrew`, but it seems like compiling HSL is a feature included in coinbrew, which is not working (please correct me if I am wrong).

PS: Also, shouldn't Metis be built before HSL?

**Comment by svigerske** [comment]
It shouldn't do this, but maybe it remembered something from a previous run that had some of the --skip options set. Maybe try doing
```
/path/to/coinbrew fetch Ipopt:stable/3.13
```
first and then do
```
/path/to/coinbrew build Ipopt:stable/3.13
```
I changed this to `stable/3.13`, because that has the fix to build Metis before HSL.

**Comment by tkralphs** [comment]
This is actually a bug. `coinbrew` tries to ensure that only projects for which the source has been downloaded are built by touching the file `.build` in the project directory after download. This is a bit of a hack---we should really just detect whether the source is there for each project by looking for an expected file like `configure` does. 

HSL never gets downloaded by `coinbrew` itself, so the special file is never created and it is never built. For right now, if you just do `touch ThirdParty/HSL/.build`, it will then build it (assuming the sources are there). I can change the detection for HSL so that it looks for an expected source file instead.

**Comment by tkralphs** [comment]
OK, I actually just put in a fix now. Can you check it? I don't have HSL at the moment to try it myself.

**Comment by iaravena** [comment]
Works. Thanks @tkralphs.

**Comment by peykaf** [comment]
Still have the same problem with ipopt 3.13.4

**Comment by peykaf** [comment]
> What version of coinbrew are you using (SHA)? If it is recent, then it should detect HSL if you have manually downloaded it. Did you do that?

I just got coinbrew following: `wget https://raw.githubusercontent.com/coin-or/coinbrew/master/coinbrew`, so it must be the latest version.

I have manually downloaded HSL. I followed IPOPT installation on [https://coin-or.github.io/Ipopt/INSTALL.html#COMPILEINSTALL](url) which says:

> To use HSL sources, change to the ThirdParty/HSL directory created by coinbrew fetch and follow the download instructions (i.e., skip the build step)

so, after fetching ipopt, I changed to ThirdParty/HSL, copied and renamed the HSL folder which I downloaded manually, and added "coinhsl" there. Then I ran `/path/to/coinbrew build Ipopt:stable/3.13` and sent you the screen shot. 

I'm not very expert in this, but it seems to me that I followed every step and it should work.

**Comment by tkralphs** [comment]
Indeed, it seems you followed the steps. Can you verify, just to be sure, that the file `ThirdParty/HSL/coinhsl/common/deps.f` is present? If it is, you could run `coinbrew` with the argument `--debug` and attach the output (which will be huge) as a file attachment to this issue. I might be able to see what's going on.

**Comment by peykaf** [comment]
> Indeed, it seems you followed the steps. Can you verify, just to be sure, that the file `ThirdParty/HSL/coinhsl/common/deps.f` is present? If it is, you could run `coinbrew` with the argument `--debug` and attach the output (which will be huge) as a file attachment to this issue. I might be able to see what's going on.

ok, upon checking `deps.f`, I had another coinhsl folder inside coinhsl, something like `ThirdParty/HSL/coinhsl/coinhsl/common/deps.f`. Perhaps due to the way I extracted the manually downloaded HSL. by cleaning this up, everything seems to be working. Thank you.

**Comment by tkralphs** [comment]
Great, thanks!
