### ISSUE TITLE
Installing COIN-OR-OptimizationSuite:releases/1.8.0 requires password for Bcps

### ISSUE THREAD

**Issue by pgirardgerad** [coin-or/coinbrew#31]
Hello,
  I'm trying to install coin-or with coinbrew and after some time I get a message asking for a github username and password.

```
Cloning into 'Bcps'...
Username for 'https://github.com': ^C
```

From what I can see, the script is trying to clone this:
`+ git clone --branch=stable/0.94 https://github.com/coin-or/CHiPPS-Bcps Bcps`

When it should be cloning this:
+ git clone --branch=stable/0.94 https://github.com/coin-or/CHiPPS-Biceps Bcps

Installing biceps on its own seems to work correctly.

**Comment by tkralphs** [comment]
Can you paste in the exact command you tried for `coinbrew` so I can replicate?

**Comment by pgirardgerad** [comment]
Sorry, I meant to paste it in my message.

`bash -x ./coinbrew build --git --parallel-jobs=6 COIN-OR-OptimizationSuite:releases/1.8.0`

**Comment by tkralphs** [comment]
The problem was that you are checking out quite an old release and the Dependencies file had an old SVN URL in it. Just to let you know, the versions of the Optimization Suite in that release are quite old by now, although there hasn't been a release of the full Optimizatoin Suite since that one. If there are particular projects you are interested in, you should get the most recent release for that project with `coinbrew`. I'll try to make a newer release with all up-to-date versions sometime soon.

**Comment by tkralphs** [comment]
Oh, I also forgot to mention that you will need to comment out the last line of the `Dependencies` file  (put a `#` at the beginning of the line), since the examples are not yet mirrored to GitHub. I will also work on that.

**Comment by tkralphs** [comment]
Never mind, I now mirrored the application templates and everything seems to be working fine.

**Comment by pgirardgerad** [comment]
Thanks for the followup. My initial problem was that I tried to compile COIN-OR-OptimizationSuite and there was an error at some point. I noticed that the script had told me at the beginning:

> NOTE: You are working with the development version.
>       You might consider the latest release version,
>       which appears to be releases/1.8.0
>       To fetch this release, execute coinbrew as
> 
>       coinbrew fetch COIN-OR-OptimizationSuite:releases/1.8.0

Which is what I did and got that git problem I posted about.

Here's what I just started:
```
git clone https://www.github.com/coin-or/coinbrew
cd coinbrew
bash -x ./coinbrew build --git --parallel-jobs=6 COIN-OR-OptimizationSuite

```
and see if that works. Since it takes a while to compile, I'll post about it later when it's done.

Since this problem has been closed, should I open a new one if something comes up or keep talking about it here? I don't use github much.

**Comment by pgirardgerad** [comment]
Here's the output. From what I can tell, it did compile Vol but failed on the unit test.

```
/tmp/coinbrew/Vol/Vol/test/OsiVolSolverInterfaceTest.cpp: In function ‘void OsiVolSolverInterfaceUnitTest(const string&, const string&)’:
/tmp/coinbrew/Vol/Vol/test/OsiVolSolverInterfaceTest.cpp:14:58: error: ‘OsiSolverInterfaceCommonUnitTest’ was not declared in this scope
     OsiSolverInterfaceCommonUnitTest(&m, mpsDir,netlibDir);
                                                          ^
In file included from /tmp/coinbrew/dist/include/coin-or/OsiSolverInterface.hpp:17:0,
                 from /tmp/coinbrew/Vol/Vol/test/../src/OsiVol/OsiVolSolverInterface.hpp:16,
                 from /tmp/coinbrew/Vol/Vol/test/OsiVolSolverInterfaceTest.cpp:6:
/tmp/coinbrew/dist/include/coin-or/CoinFinite.hpp: At global scope:
/tmp/coinbrew/dist/include/coin-or/CoinFinite.hpp:18:14: warning: ‘COIN_DBL_MIN’ defined but not used [-Wunused-variable]
 const double COIN_DBL_MIN = (std::numeric_limits< double >::min)();
              ^
/tmp/coinbrew/dist/include/coin-or/CoinFinite.hpp:19:14: warning: ‘COIN_DBL_MAX’ defined but not used [-Wunused-variable]
 const double COIN_DBL_MAX = (std::numeric_limits< double >::max)();
              ^
/tmp/coinbrew/dist/include/coin-or/CoinFinite.hpp:20:11: warning: ‘COIN_INT_MAX’ defined but not used [-Wunused-variable]
 const int COIN_INT_MAX = (std::numeric_limits< int >::max)();
           ^
/tmp/coinbrew/dist/include/coin-or/CoinFinite.hpp:21:14: warning: ‘COIN_INT_MAX_AS_DOUBLE’ defined but not used [-Wunused-variable]
 const double COIN_INT_MAX_AS_DOUBLE = (std::numeric_limits< int >::max)();
              ^
make[1]: *** [OsiVolSolverInterfaceTest.o] Error 1
make: *** [test] Error 2

Build failed, see error output above

```

**Comment by pgirardgerad** [comment]
That configuration command failed in Vol because of the unit tests. So I changed the options to remove the tests and I now have an error in SYMPHONY.

```
##################################################
### Building SYMPHONY master
##################################################

In file included from /tmp/coinbrew/SYMPHONY/SYMPHONY/src/OsiSym/SymWarmStart.hpp:22:0,
                 from /tmp/coinbrew/SYMPHONY/SYMPHONY/src/OsiSym/SymWarmStart.cpp:19:
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:11:27: error: aggregate 'COINUTILSLIB_EXPORT CoinWarmStartDiff' has incomplete type and cannot be defined
 class COINUTILSLIB_EXPORT CoinWarmStartDiff;
                           ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:21:27: error: variable 'COINUTILSLIB_EXPORT CoinWarmStart' has initializer but incomplete type
 class COINUTILSLIB_EXPORT CoinWarmStart {
                           ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:21:27: warning: extended initializer lists only available with -std=c++11 or -std=gnu++11 [enabled by default]
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:22:1: error: expected primary-expression before 'public'
 public:
 ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:22:1: error: expected '}' before 'public'
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:22:1: error: expected ',' or ';' before 'public'
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:27:11: error: 'CoinWarmStart' does not name a type
   virtual CoinWarmStart *clone() const = 0;
           ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:29:11: error: 'CoinWarmStartDiff' does not name a type
   virtual CoinWarmStartDiff *
           ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:33:19: error: 'CoinWarmStartDiff' does not name a type
   applyDiff(const CoinWarmStartDiff *const) {}
                   ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:33:38: error: ISO C++ forbids declaration of 'parameter' with no type [-fpermissive]
   applyDiff(const CoinWarmStartDiff *const) {}
                                      ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:33:43: error: 'virtual' outside class declaration
   applyDiff(const CoinWarmStartDiff *const) {}
                                           ^
/tmp/coinbrew/dist/include/coin-or/CoinWarmStart.hpp:34:1: error: expected declaration before '}' token
 };
 ^
make[1]: *** [SymWarmStart.lo] Error 1
make: *** [all-recursive] Error 1

Build failed, see error output above

```

**Comment by svigerske** [comment]
I added some commits to CoinUtils/trunk and Vol/trunk that may help on these. It seems to take some time until they make it to GitHub.
