### ISSUE TITLE
coinbrew build error at Ipopt

### ISSUE THREAD

**Issue by holyorevil** [coin-or/coinbrew#32]
There are errros When I build Ipopt master. my link is /d/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.16.27023/bin/HostX64/x64/link. ther error message is 
##################################################
##################################################

Making all in src/Common
make[1]: Entering directory '/f/ipopt/coinbrew-master/build/Ipopt/master/src/Common'
make  all-am
make[2]: Entering directory '/f/ipopt/coinbrew-master/build/Ipopt/master/src/Common'
/bin/sh ../../libtool  --tag=CXX   --mode=compile /f/ipopt/coinbrew-master/Ipopt/compile icl -DHAVE_CONFIG_H -I. -I/f/ipopt/coinbrew-master/Ipopt/src/Common  -DIPOPT_BUILD -IC:\Program -IFiles -I(x86)\Java\jdk1.8.0_144/include -IC:\Program -IFiles -I(x86)\Java\jdk1.8.0_144/include/win32  -nologo -EHs -DNDEBUG -O2 -MD  -c -o IpDebug.lo /f/ipopt/coinbrew-master/Ipopt/src/Common/IpDebug.cpp
/bin/sh: -c: line 0: syntax error near unexpected token `('
/bin/sh: -c: line 0: `/bin/sh ../../libtool  --tag=CXX   --mode=compile /f/ipopt/coinbrew-master/Ipopt/compile icl -DHAVE_CONFIG_H -I. -I/f/ipopt/coinbrew-master/Ipopt/src/Common  -DIPOPT_BUILD -IC:\Program -IFiles -I(x86)\Java\jdk1.8.0_144/include -IC:\Program -IFiles -I(x86)\Java\jdk1.8.0_144/include/win32  -nologo -EHs -DNDEBUG -O2 -MD  -c -o IpDebug.lo /f/ipopt/coinbrew-master/Ipopt/src/Common/IpDebug.cpp'
make[2]: *** [Makefile:518: IpDebug.lo] Error 1
make[2]: Leaving directory '/f/ipopt/coinbrew-master/build/Ipopt/master/src/Common'
make[1]: *** [Makefile:408: all] Error 2
make[1]: Leaving directory '/f/ipopt/coinbrew-master/build/Ipopt/master/src/Common'
make: *** [Makefile:647: all-recursive] Error 1

by the way,Some warnings are worth mentioning.the warnings occur when build Mumps

/bin/sh ./libtool    --mode=link /f/ipopt/coinbrew-master/ThirdParty/Mumps/compile ifort  -nologo -fpp -O2 -MD   -version-number 2:0:0 -no-undefined  -o libcoinmumps.la -rpath /f/ipopt/coinbrew-master/dist/lib MUMPS/src/tools_common_mod.lo MUMPS/src/dmumps_comm_buffer.lo MUMPS/src/dmumps_struc_def.lo MUMPS/src/mumps_ooc_common.lo MUMPS/src/mumps_static_mapping.lo MUMPS/src/dmumps_ooc_buffer.lo MUMPS/src/dmumps_load.lo MUMPS/src/dmumps_ooc.lo MUMPS/src/dmumps_part1.lo MUMPS/src/dmumps_part2.lo MUMPS/src/dmumps_part3.lo MUMPS/src/dmumps_part4.lo MUMPS/src/dmumps_part5.lo MUMPS/src/dmumps_part6.lo MUMPS/src/dmumps_part7.lo MUMPS/src/dmumps_part8.lo MUMPS/src/mumps_part9.lo MUMPS/src/mumps_sol_es.lo MUMPS/src/mumps_c.lo MUMPS/src/mumps_common.lo MUMPS/src/mumps_orderings.lo MUMPS/src/mumps_io.lo MUMPS/src/mumps_io_basic.lo MUMPS/src/mumps_io_thread.lo MUMPS/src/mumps_io_err.lo MUMPS/src/mumps_size.lo MUMPS/libseq/mpi.lo MUMPS/libseq/mpic.lo MUMPS/libseq/elapse.lo mkl_intel_lp64_dll.lib mkl_sequential_dll.lib mkl_core_dll.lib

*** Warning: Linking the shared library libcoinmumps.la against the
*** static library mkl_intel_lp64_dll.lib is not portable!

*** Warning: Linking the shared library libcoinmumps.la against the
*** static library mkl_sequential_dll.lib is not portable!

*** Warning: Linking the shared library libcoinmumps.la against the
*** static library mkl_core_dll.lib is not portable!
Could these Warnings have any affect?

**Comment by svigerske** [comment]
There are spaces in the path to Java, which seem to generate trouble.
If you do not need the Java interface of Ipopt, then try again after adding the option `--disable-java` to your coinbrew call.

The warnings about linking against the mkl-dll-lib files can be ignored. I don't know how to suppress these, but so far they didn't cause problems.

**Comment by holyorevil** [comment]
it woreks!!thank you very much!!!
