### ISSUE TITLE
LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by jamie0walton** [coin-or/coinbrew#37]
Running a pretty clean debian 10.3. Tried coinbrew. Nice.

./coinbrew fetch SYMPHONY:releases/5.6.17
./coinbrew build --no-prompt SYMPHONY --prefix=/usr/local/bin --verbosity=1

Though I got the error

./coinbrew: line 1161: LD_LIBRARY_PATH: unbound variable

Reverting your recent change fixed it so I expect that in my system LD_LIBRARY_PATH was not defined and the shell could not find it.

**Comment by tkralphs** [comment]
Argh, yeah, never accept a PR, not matter how simple, unless testing first! Sure, we have to check whether LD_LIBRARY_PATH is already set. Should be fixed now.
