### ISSUE TITLE
Various errors on MacOS (Mojave)

### ISSUE THREAD

**Issue by crbinz** [coin-or/coinbrew#38]
First, cc905f64c39 introduces an error:
```
./coinbrew: line 1161: conditional binary operator expected
./coinbrew: line 1161: syntax error near `LD_LIBRARY_PATH'
./coinbrew: line 1161: `        if [[ -v LD_LIBRARY_PATH ]]; then'
```
reverting this change got rid of the error for me

Second, I get an unbound variable error around Line 1375, I got around this by commenting out `set -u`.

**Comment by tkralphs** [comment]
I guess this is because of the old version of bash on MacOS. Installing a modern one with Homebrew should fix this issue.

**Comment by crbinz** [comment]
Yes, it looks like that was the issue - installing a newer bash with Homebrew seems to have fixed the issues. Thanks for the quick responses.
