### ISSUE TITLE
Install instructions

### ISSUE THREAD

**Issue by tristansharp** [coin-or/coinbrew#4]
Using coinbrew to help download and compile everything seems very useful, but after some output I get the following error:
./coinbrew fetch --main-proj=Clp
error: pathspec 'trunk/CoinUtils' did not match any file(s) known to git.

**Comment by tkralphs** [comment]
Ah, OK, fixed now by a623e5bfefeaba35e7794fa10ec916d36b4d5bb1. I was able to replicate this. It happens with `git` if you try to use the script to update an existing checkout and one of the projects is on master. There was one place where the conversion from `trunk` to `master` was not being done properly. No idea how this managed to slip through. Thanks for pointing it out!

By the way, you can pass any configure options you want to coinbrew, so if you need static libraries, just do
```
$ ./coinbrew build --main-proj=Clp --disable-shared --enable-static
```

**Comment by tristansharp** [comment]
I verified that this works for me now.

**Comment by tkralphs** [comment]
Thanks!
