### ISSUE TITLE
How to build only a ThirdParty

### ISSUE THREAD

**Issue by Behemoth-s** [coin-or/coinbrew#42]
I was tring to build Mumps using coinbrew
```./coinbrew build ThirdParty/Mumps --enable-msvc --verbosity=3 --build=x86_64-w64-mingw32 --prefix=dist/bonmin --build-dir=build/bonmin```
and I got 
```
Package will be built in /c/Personal/project/bonmin/build
Package will be installed to /c/Personal/project/bonmin/dist
Caching configuration options...
./coinbrew: line 1402: /c/Personal/project/bonmin/build/.config/ThirdParty/Mumps-master: No such file or directory
```
However, if I build a coin project dependent on Mumps，such as Ipopt.
```
./coinbrew build Ipopt --enable-msvc --verbosity=3 --build=x86_64-w64-mingw32 --prefix=dist/bonmin --build-dir=build/
bonmin
```
Mumps will be built successfully meantwhile.

**Comment by svigerske** [comment]
Probably that should be `ThirdParty-Mumps` instead of `ThirdParty/Mumps`.

The usefulness of coinbrew to build a project that has no dependencies is not clear to me, though.

**Comment by Behemoth-s** [comment]
> Probably that should be `ThirdParty-Mumps` instead of `ThirdParty/Mumps`.
> 
> The usefulness of coinbrew to build a project that has no dependencies is not clear to me, though.

`ThirdParty-Mumps` is recognized as a project name, still not work.
emmm, it seems not too much use， I just want to check if there is such a feature

**Comment by tkralphs** [comment]
I don't think there is any restriction to a specific list of projects. Anyone could make a project that would work with `coinbrew`, but it is assumed that the project has a file called `Dependencies`. I don't see any reason, actually why the non-existence of this file should cause an error, though. If someone wants to use `coinbrew` to fetch and build a single project, that should be fine.

I thought of adding the ability to build a sequence of projects specified on the command line (sort of like specifying a list of dependencies yourself) and then it would actually be required to be able to build individual projects with no dependencies. Anyway, for now, it's not possible, but perhaps in the future.

**Comment by Behemoth-s** [comment]
Thanks for explanation

**Comment by tkralphs** [comment]
Actually, I now realized that if you do `--skip-dependencies`, it should build even without a `Dependencies` file in the current version. I've already changed so that the file is not required in any case in my local version, but I'm not going to push that change until I do some more testing.

**Comment by tkralphs** [comment]
FYI, I just made a bunch of update to coinbrew and this behavior has now been changed. You can now build a project that doesn't have a `Dependencies` file.
