### ISSUE TITLE
On Linux, running fetch, build and install separately fails, but running them all together works

### ISSUE THREAD

**Issue by eli-b** [coin-or/coinbrew#45]
Using coinbrew to build Osi, running
```
/path/to/coinbrew fetch --main-proj=Osi
/path/to/coinbrew build --main-proj=Osi --test
/path/to/coinbrew install --main-proj=Osi
```
as directed by Osi' README.md, fails during the `install` stage because it tries to change into subdirectories like DEPENDENCY/OSI_VERSION_NUMBER instead of DEPENDENCY/DEPDENCY_VERSION_NUMBER.

The workaround I found was to run all three stages together:
`/path/to/coinbrew fetch build install --main-proj=Osi`

**Comment by tkralphs** [comment]
The install step is now incorporated into the build process, so you no longer need to run it explicitly (even the fetch step is run automatically when you build). I now updated the README. But you are correct that the explicit install step is slightly broken and I will fix that.
