### ISSUE TITLE
Still unable to build a static executable (for debugging by gdb purpose)

### ISSUE THREAD

**Issue by ebni** [coin-or/coinbrew#46]
Dear all,

sorry to bother you with something that seems you solved, but I lost two full days trying all possible permutations with coinbrew/configure/library paths options.
I'm having a very hard time to get an stand-alone executable (with statically linked libraries) which just solves your `driverC.c` example. I was able to use and debug GLPK code very smoothly. A colleague suggested me to switch to your library, which seems more actively supported than GLPK. The hardness to run step by step (by gdb) your libraries is however, becoming a huge obstacle.
Any hint or advice?

Best,

Enrico

PS: sorry, if this is the wrong communication channel with you.

**Comment by tkralphs** [comment]
I guess you're talking about Cbc? `coinbrew` can be used to build many different packages. Building static libraries for debugging purposes is a different problem than building a fully static executable. To build static libraries for debugging, just add `--enable-debug` as an argument to `coinbrew`, as described, e.g., [here](https://coin-or.github.io/user_introduction#linux-1).

**Comment by tkralphs** [comment]
Also, to build the examples, build Cbc first, then go into the `build/Cbc/<version>/examples` directory and do, e.g., `make DRIVER=driver`. I'm not sure what version you're using exactly.

**Comment by ebni** [comment]
Thanks for the clarification. I'll try to follow your pointers.
Enrico

**Comment by bradbell** [comment]
I am having similar trouble with coinbrew. Looking at
https://coin-or.github.io/user_introduction.html
the coinbrew flags --enable-debug and --disable-shared should work.  
My tests indicate that coinbrew is not passing through flags like --enable-debug and --disable-shared. 

For example, if I execute the following commands
```
rm -r /home/bradbell/prefix/dismod_at/lib64
./coinbrew fetch Ipopt@3.13.2 --no-prompt
./coinbrew build Ipopt@3.13.2 --enable_debug --enable-static --disable-shared --test --no-prompt --verbosity=3 --prefix=/home/bradbell/prefix/dismod_at --libdir=/home/bradbell/prefix/dismod_at/lib64 ADD_FCFLAGS=-fallow-argument-mismatch
ls /home/bradbell/prefix/dismod_at/lib64
 ```
The resulting output is:
```
libcoinasl.la        libcoinmumps.so.2.1.0            libipopt.so.3
libcoinasl.so        libipoptamplinterface.la         libipopt.so.3.13.2
libcoinasl.so.2      libipoptamplinterface.so         libsipopt.la
libcoinasl.so.2.0.0  libipoptamplinterface.so.3       libsipopt.so
libcoinmumps.la      libipoptamplinterface.so.3.13.2  libsipopt.so.3
libcoinmumps.so      libipopt.la                      libsipopt.so.3.13.2
libcoinmumps.so.2    libipopt.so                      pkgconfig
```

**Comment by tkralphs** [comment]
This report isn't really related to the original bug report, which has to do with static executables, not static libraries. But in any case, with Ipopt `master`, you just need `--enable-debug` and `--disable-shared`, not `--static`. The `--static` flag is a `coinbrew` flag, not a `configure` flag and it's to add flags needed for building static executables, which is a whole different thing. I guess the problem you're running into is that the `--static` flag is causing some configure options to be added that don't work with Ipopt for some reason. If I do
```
coinbrew build Ipopt --enable-debug --disable-shared
```
everything goes through fine and I get static libraries.

**Comment by bradbell** [comment]
Works for me. 
Thanks.
