### ISSUE TITLE
Unable to install Clp dependencies

### ISSUE THREAD

**Issue by dmj2144** [coin-or/coinbrew#5]
I am trying to install clp and its' dependencies but, when I execute the install command it gives the following error message:

"libtool: install: error: cannot install `libcoinlapack.la' to a directory not ending in /root/build/lib"

I simply execute the following:

./coinbrew/coinbrew fetch --main-proj=Clp
./coinbrew/coinbrew build--main-proj=Clp --disable-shared --enable-static --prefix=/usr
./coinbrew/coinbrew install --main-proj=Clp

I am not too sure where I am doing wrong but, I am executing all these commands within a Docker container if that helps.

Thoughts ?
Dennis

**Comment by tkralphs** [comment]
Yeah, my method of staging the install seems to be broken. I swear it was working before. This should be fixed by #6. Can you give it a try?

**Comment by tkralphs** [comment]
Fixed by 85cfa34cdca9d4fea4384ec8d9982dd6d5c47539.
