### ISSUE TITLE
When using "fetch", can't switch from release to master.

### ISSUE THREAD

**Issue by rschwarz** [coin-or/coinbrew#50]
I used coinbrew to `fetch` the latest release version of Cbc and all dependencies.
Then I realized that I want the master branch instead.

But now, when I go through fetch and enter `master` as prefered version, I get this error:

```
Please enter another version name in the form of
master, releases/x.y.z, or stable/x.y
=> master


##################################################
### Switching Cbc to master and rebasing 
##################################################

You are not currently on a branch.
Please specify which branch you want to rebase against.
See git-pull(1) for details.
```

I think this is because when the latest release version was checked out previously, it was referenced by the git commit hash, so the [git pull --rebase](https://github.com/coin-or/coinbrew/blob/master/coinbrew#L1000) fails.

The fix is to first `git checkout master`, switching to a proper branch, before running the `pull`, which has to be done for all dependencies as well.

I got it working by inserting:
```
@@ -995,6 +995,7 @@ function fetch_proj {
                 git checkout $(git rev-list -n 1 --first-parent --before="$checkout_time" \
                                    remotes/origin/$version)
             else
+                git checkout $version
                 if [ $rebase = "true" ]; then
                     print_action "Switching $dir to $version and rebasing"
                     git pull --rebase
```
but I don't know whether that would break in some other situation.

**Comment by tkralphs** [comment]
Oh goodness, thanks for reporting this. The situation you mentioned is actually accounted for in the script, but a bug was introduced in a badly botched commit (3e0c49dc) several months ago that introduced an option to pull with rebase. This should be fixed by d90c9cc4.

**Comment by tkralphs** [comment]
By the way, if you want to switch versions to `master` you can also just do
```
git fetch Cbc@master
```
in an existing checkout and avoid the need to interactively enter the version.

**Comment by rschwarz** [comment]
Thanks. I also appreciate the ability to compile everything with dependencies in debug mode, in one go :heart:
