### ISSUE TITLE
Where can I find the .clang-format file that is applied to format COIN-OR code

### ISSUE THREAD

**Issue by dpar39** [coin-or/coinbrew#54]
I see the script format-source.sh calls `clang-format -i -style=file $file` but I can't find the .clang-format that is applied.

**Comment by tkralphs** [comment]
Sorry for the late reply to this. Where is the `format-source.sh` script that you're talking about? In general, we don't have a single standard across the Optimization Suite for source formatting and have been very lax about using tools like clang-reformat to keep source consistently formatted. That is something we should definitely do.

**Comment by dpar39** [comment]
I found a .clang-format in cbc: https://github.com/coin-or/Cbc/blob/master/.clang-format and most of the repos have a `format-source.sh` like this one: https://github.com/coin-or/Clp/blob/master/src/format-source.sh
