### ISSUE TITLE
ftp downloads sometimes stall at 99% (or even 100%)

### ISSUE THREAD

**Issue by dlaehnemann** [coin-or/coinbrew#56]
When running `coinbrew fetch Cbc@master`, the process sometimes stalls while downloading packages via ftp, e.g.:
```
##################################################
### Fetching ThirdParty/Glpk master
##################################################

Cloning into 'ThirdParty/Glpk'...
remote: Enumerating objects: 1362, done.
remote: Total 1362 (delta 0), reused 0 (delta 0), pack-reused 1362
Receiving objects: 100% (1362/1362), 1.62 MiB | 592.00 KiB/s, done.
Resolving deltas: 100% (915/915), done.

Running script to download the source code for GLPK 4.65.

Downloading the source code from ftp.gnu.org...
--2021-02-26 17:05:42--  http://ftp.gnu.org/gnu/glpk/glpk-4.65.tar.gz
Resolving ftp.gnu.org (ftp.gnu.org)... 209.51.188.20, 2001:470:142:3::b
Connecting to ftp.gnu.org (ftp.gnu.org)|209.51.188.20|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4167110 (4.0M) [application/x-gzip]
Saving to: ‘glpk-4.65.tar.gz’

glpk-4.65.tar.gz                                99%[================================================================================================> ]   3.97M  --.-KB/s    eta 0s
```
Nothing happens thereafter and I then have to abort (`Ctrl-c`) and restart the fetching.

**Comment by tkralphs** [comment]
Unfortunately, there's not much we can do about this. The code is being fetched from a third-party server not under our control. We might be able to implement a timeout and mirror the code to Github if it becomes to much of a problem. We have done that in other cases. 

Note that if you are not using the functionality provided by GLPK (parsing of GMPL files, mainly), then you can just avoid downloading it altogether with `--skip=ThirdParty/Glpk` or `-no-third-party` (the latter will obviously also disable downloading of other third-party codes).

**Comment by dlaehnemann** [comment]
Yeah, this definitely isn't high priority. So feel free to close this, at least this issue documents it and gives some suggestions. Or keep it open, if you want to implement any of the workarounds later. But maybe GLPK and the other third party projects will also have a more stable home at some point...

**Comment by tkralphs** [comment]
OK, I will close for now. Thanks!
