### ISSUE TITLE
testing `yaml` branch building of `Cbc@master`: works

### ISSUE THREAD

**Issue by dlaehnemann** [coin-or/coinbrew#57]
As [promised over in a `CoinUtils` issue](https://github.com/coin-or/CoinUtils/issues/147#issuecomment-785184357), I have just tested out building `Cbc` with the `coinbrew` version in the `yaml` branch, particularly at commit f83d1bfac9ddd4839b7b9c11a3713426721625fb. Since there's no PR open for that branch to post to, I figured an issue is probably best for reporting this test.

I was looking at building the current `master` branch of `Cbc` (at commit fda2cad9e452a8d6721c05e41c9fd742f6bc5275) and the fetching and building with the following commands worked fine up until `Cbc`:
```
coinbrew fetch Cbc@master --no-prompt
coinbrew build Cbc@master ADD_CXXFLAGS=-DCBC_THREAD_SAFE --prefix=/path/to/cbc/install --no-prompt
```

This works, just like building with the `coinbrew` `master` branch.

**Comment by dlaehnemann** [comment]
Also, a quick test with the [`big_problem` file](https://github.com/coin-or/CoinUtils/issues/147#issue-812220796) I used to report some bugs over at `CoinUtils` ran through nicely. So the `yaml` also pulls in the latest `CoinUtils` commits, as well.

**Comment by tkralphs** [comment]
Good idea to open a draft PR to comment on. Since no one was looking before, I didn't bother with it :). I should have mentioned that you currently have to specify `--yaml` to get it to read `config.yml` file instead of `Dependencies`. Since it's my intention to make this the default when there is a `config.yml` present, though, I should probably make it the default in this branch. I'll make that change. 

I so expect it to work with a straightforward fetch, since I do that myself all the time. I'm hoping to get some testing on edge cases by getting other people to stress test it. 

I did mix in some other experimental things, which I should probably do in separate branches, but I want to be able to test all these things at the same time by just using the `yaml` branch day to day. Look for a draft PR later on.

**Comment by dlaehnemann** [comment]
# current master works

So, this also runs through without issue (no `fetch`, just directly the `build`):
```
coinbrew build --yaml Cbc@master ADD_CXXFLAGS=-DCBC_THREAD_SAFE --prefix=/path/to/cbc/install --no-prompt
```
# releases don't work

I then randomly went for some older version, after having done the above build:
```
coinbrew build Cbc@2.7.0 ADD_CXXFLAGS=-DCBC_THREAD_SAFE --yaml --prefix=/path/to/cbc/install --no-prompt --reconfigure
```
But despite the `--reconfigure` this just recompiles the current `Cbc@master`. I then tried with a `fetch`, beforehand:
```
coinbrew fetch Cbc@2.7.0 --yaml
coinbrew build Cbc@2.7.0 ADD_CXXFLAGS=-DCBC_THREAD_SAFE --yaml --prefix=/path/to/cbc/install --no-prompt --reconfigure
```
This switched `Cbc` to its version `2.7.0`, but kept all other projects at the current `master` branch. This, in turn, led to a header file not being found during compilation of `Cbc`.

I then went for a clean slate, removing all the previously fetched and built files, and retried directly with the build command. But this runs into issues during the `Cbc` configuration step.

To get a clearer error message, I switched to fetching first:
```
coinbrew fetch --yaml Cbc@2.7.0
```
This gives:
```
No dependencies file found, only main project will be built
```
And I see the same error message for a number of specific versions up to (and including) the most recent release `2.10.5`.

Now, I guess this makes sense, as the respective `yaml` file is not present for those versions, right? So the `yaml` approach will only work for future versions? And this is probably at the root of all of the above problems?

# conda-forge build recipe works

As another test case on the current master branch, I emulated the build recipe for the `coin-or-cbc` feedstock on `conda-forge:
https://github.com/conda-forge/coin-or-cbc-feedstock/blob/b50855300c9b1f6096f46d26169515a7c1243a41/recipe/build.sh

Running the corresponding `coinbrew` command works fine:
```
coinbrew build --yaml Cbc@master --with-lapack-lib="-llapack" --enable-cbc-parallel --enable-gnu-packages --with-blas-lib="-lblas" --prefix=/vol/tiny/laehnemann/cbc/install --no-prompt
```

**Comment by tkralphs** [comment]
Cool,, thanks, that is some good stress testing. I'm not sure all of that would work even with coinbrew in `master`. The `--yaml` argument shouldn't have any effect for older version of Cbc, which wouldn't have `config.yml`. Even releases in the 2.10 series don't have it, as it didn't exist at the time they were made.

**Comment by tkralphs** [comment]
I now opened a [draft PR](#58) for the YAML parsing functionality.

**Comment by dlaehnemann** [comment]
Then I'll just close this, in favour of discussions at the PR. Also, I probably won't have much more time to stress test any time soon. But looking forward to all the upcoming changes here and in the other `COIN-OR` projects!
