### ISSUE TITLE
Downloading binaries - Bintray service close

### ISSUE THREAD

**Issue by snio89** [coin-or/coinbrew#59]
coinbrew uses `wget https://bintray.com/coin-or/download/download_file?file_path=$download_file` to download binaries. And Bintray will close its service from May 1st [#](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). Another repository may be required.

**Comment by tkralphs** [comment]
Thanks for the heads up, I had missed this. This requires some thought. There are a lot of balls in the air regarding support for installation of binaries on different platforms and it's not clear what ones to put effort into. Uploading artifacts directly to Github is a possibility, but would require some effort to automate. It would be good to start a discussion about this and get some community help and feedback.

**Comment by xmunoz** [comment]
I think that is a good short-to-medium term solution, and something that I'm going to start sending PRs for soon, starting with CoinUtils.

**Comment by tkralphs** [comment]
For now, I posted binaries on our old Web server here (where there already some old ones): 

https://www.coin-or.org/download/binary/Cbc/

Once I download the binaries for a few other projects, I can fix the coinbrew download link, but the binary download option was a somewhat undocumented feature that I assumed no one was really using. If we move to conan, then it will be moot anyway.

**Comment by snio89** [comment]
I thought using Github was a nice idea since maintaining the server may require additional efforts, which is not the thing I intended when I posted this issue. 

Mentions about Bintray seem like only existing in some packages: [user_introduction](https://coin-or.github.io/user_introduction), [Cbc/readme](https://github.com/coin-or/Cbc/blob/master/README.md), [Cbc/.coin-or/generate_readme](https://github.com/coin-or/Cbc/blob/master/.coin-or/generate_readme), and [python-mip/releases/tag/1.8.0](https://github.com/coin-or/python-mip/releases/tag/1.8.0). And I think only a few external projects use Bintray: [or-tools/issues/1919](https://github.com/google/or-tools/issues/1919) and [calliope/.azure-pipelines.yml](https://github.com/calliope-project/calliope/blob/master/.azure-pipelines.yml).

I agree that the need for binary downloading option may not that high. In case of Cbc, apt and brew can be used in Linux and Mac, respectively. Therefore, if maintaining the binary download service requires to much effort, I think temporarily/permanently stop the service may not be an issue for most users (except Windows ones...).

**Comment by tkralphs** [comment]
We are working on automated build and test with Github Actions, which should resolve this. I'm going to close this for now, feel free to reopen if needed.
