### ISSUE TITLE
Replace this repository with conan.io

### ISSUE THREAD

**Issue by xmunoz** [coin-or/coinbrew#60]
A cursory amount of research suggests that http://conan.io/ has emerged as the preferred package management solution for C/C++. That fact that this repository exists as a one-off hack to the C-dependency-management problem makes me shudder. So yeah, let's talk about alternatives.

**Comment by tkralphs** [comment]
Haha, what makes me shudder is thinking of how much time I've put into this "one-off hack" :). But seriously, I did actually look at conan and some other solutions before diving in and determined that it/they lacked features that I (and other developers) need to manage COIN-OR projects. For users, though, it is probably a good option. At the time I started work on coinbrew, I didn't want to put the time into conan when I would also still need to develop coinbrew for myself. Now coinbrew i working fine for my purposes and if we can get conan set up, too, then that is probably a win for users. Although I will point out that it is a product of the same company that just pulled the rug out from under us by closing down Bintray :). Forunately, it's open source so I guess it can't easily go away. It would be great to see if we can make it work.

**Comment by xmunoz** [comment]
> Although I will point out that it is a product of the same company that just pulled the rug out from under us by closing down Bintray :)

Yikes! That is definitely a reason to be suspicious.

Well, let's leave this issue open for now, maybe with a less prescriptive title, as a place to discuss open source dependency management alternatives.

**Comment by xmunoz** [comment]
Actually, now realizing that this is probably a more of a Discussion than an issue. Closing and moving there.
