### ISSUE TITLE
coinbrew install of ipopt broken

### ISSUE THREAD

**Issue by bradbell** [coin-or/coinbrew#71]
On 2022-03-27 I did the following:
```
wget https://raw.githubusercontent.com/coin-or/coinbrew/v1.0/coinbrew
chmod +x coinbrew
./coinbrew fetch Ipopt@3.13.2 --no-prompt
./coinbrew -j 3 build Ipopt@3.13.2 --prefix=/home/bradbell/prefix/ipopt --test --no-prompt --verbosity=3 
```
If I then execute the command
```
cat $( find ~/prefix/ipopt -name 'ipopt.pc' )
```
the output will include the line
```
Requires.private: coinmumps lapack blas
```
If I try to use the installed version of ipopt I will get a message that coinmumps.pc cannot be found. (This method of installing this version of Ipopt used to work)

**Comment by tkralphs** [comment]
Thanks for the report, but I'm not sure exactly what you're doing that did not work as you expected it to. You said you are "using the installed version of Ipopt," but normal usage would not require locating `coinmumps.pc`. What exactly are you doing and what exactly is the error (cut and paste the actual command sequence and the precise error). A little preprocessing would also help. Is `coinmumps.pc` where you expect it to be or not? Not being able to find `coinmumps.pc` doesn't always mean it's not there, it could also mean that `PKG_CONFIG_PATH` is not set properly, for example.

**Comment by bradbell** [comment]
You are correct. For my test case (above), coinmumps.pc is installed, but for my actual case it is not. I am going to be more careful about isolating the problem and get back to you.

**Comment by bradbell** [comment]
The problem I was having was due to having a second install of Ipopt with a different prefix. In this case, the install sometimes did not include coinmumps.pc. Then later, when the PKG_CONFIG_PATH changed to the new install directory, coinmumps.pc was missing. This was totally my error and so I am closing this bug.
