### ISSUE TITLE
Error when installing with coinbrew

### ISSUE THREAD

**Issue by MajidSKhoshghalb** [coin-or/coinbrew#76]
Hey Guys,

I am receiving this error when installing with coinbrew:

`##################################################
##################################################

/usr/bin/ld: /home/user/Desk/All2/build/Ipopt/3.12/src/Interfaces/.libs/libipopt.so: undefined reference to `_gfortran_transfer_integer_write'
/usr/bin/ld: /home/user/Desk/All2/build/Ipopt/3.12/src/Interfaces/.libs/libipopt.so: undefined reference to `_gfortran_transfer_character_write'
/usr/bin/ld: /home/user/Desk/All2/build/Ipopt/3.12/src/Interfaces/.libs/libipopt.so: undefined reference to `_gfortran_st_write_done'
/usr/bin/ld: /home/user/Desk/All2/build/Ipopt/3.12/src/Interfaces/.libs/libipopt.so: undefined reference to `_gfortran_string_len_trim'
/usr/bin/ld: /home/user/Desk/All2/build/Ipopt/3.12/src/Interfaces/.libs/libipopt.so: undefined reference to `_gfortran_stop_string'
/usr/bin/ld: /home/user/Desk/All2/build/Ipopt/3.12/src/Interfaces/.libs/libipopt.so: undefined reference to `_gfortran_st_write'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:497: ipopt] Error 1
make[1]: *** [Makefile:379: all-recursive] Error 1
make: *** [Makefile:679: all-recursive] Error 1`

I am using a machine with Windows 11 with UBUNTU 20.04 in WSL2  using this command:
`sudo ./coinbrew build --without-mumps --prefix=/usr/local/lib --tests none`

I did it 2 months ago and it worked perfectly. Any idea? Thanks in advance!

**Comment by svigerske** [comment]
I already wonder how coinbrew would know that it should build the old Ipopt 3.12 from the command you specify. There is no mention of Ipopt in it.

Not sure what goes wrong, but you could try working around by adding something like `LDFLAGS=-lgfortran` to your coinbrew call.

**Comment by MajidSKhoshghalb** [comment]
Thanks a lot for your quick reply, worked.
