### ISSUE TITLE
Fails to run libCgl unit tests with msys and --enable-msvc

### ISSUE THREAD

**Issue by scott-c-h** [coin-or/coinbrew#80]
Running  

`./coinbrew build Cbc@2.10.8 --enable-msvc --enable-shared --no-third-party --build=x86_64-w64-mingw32`

I get:

```
##################################################
### Running Cgl unit test
##################################################

cl : Command line warning D9035 : option 'o' has been deprecated and will be removed in a future release
make[1]: *** [Makefile:434: unitTest.exe] Error 2
make: *** [Makefile:871: test] Error 2

Error: Build failed, see error output above
```

Running `make` in the test directory shows that that there are heaps of unresolved externals relating the `libCgl*` libraries.
It looks like the process to create libCgl doesnt work and is missing some of the objects in the libCgl* archives.

I can get the build process to work by running `lib -OUT:.libs/libCgl.lib `find -name "*.obj"` in the build/Cgl/0.60.6/src directory. Then re-running the build works from that point.

**Comment by tkralphs** [comment]
Looks like I overlooked this issue wen it was filed some time ago. What were you hoping for with the option `--enable-shared`? Cbc 2.10 doesn't support creation of DLLs and the way to control which run-time is used is by arguments to `--enable-msvc`. By default you get the `MT` flag to `cl` and if you want `MD`, you should do `--enable-msvc=MD`. Similarly, you can get `MDd` and `MTd` by adding `--enable-debug`. It's a little confusing, but using `--enable-shared`  with `--enable-msvc` in version 2.10 doesn't really make sense. This is all much more logical in `master`, where creation of DLLs is supported.

**Comment by scott-c-h** [comment]
Thanks for your response - what I was after was `--enable-msvc=MD` for compatibility with existing code.
