### ISSUE TITLE
coinbrew fails wis OSI on OSX, apparently due to not finding Cplex

### ISSUE THREAD

**Issue by frangio68** [coin-or/coinbrew#86]
Hi.

Everything has been going well for me for ages with coinbrew, but now it's failing to properly install OSI (via CBC).

The full log is at the bottom. Apparently if fails to find CPXgetstat(). But I'm passing it the right path

--with-cplex-lib=-L/Users/frangio/Applications/CPLEX_Studio221/cplex/lib/x86-64_osx/static_pic/ -lcplex -lm

as the log confirms, and the stuff is there

ls /Users/frangio/Applications/CPLEX_Studio221/cplex/lib/x86-64_osx/static_pic
libcplex.a libilocplex.a

To be on the safe side I added the path to DYLD_LIBRARY_PATH

set | fgrep DYLD
DYLD_LIBRARY_PATH=/Users/frangio/Applications/SCIPOptSuite-8.0.3-Darwin/lib:/Users/frangio/Applications/CPLEX_Studio221/cplex/lib/x86-64_osx/static_pic:/Library/gurobi1002/macos_universal2/lib

Everything should be current, I have the latest (I guess) Xcode and clang

Version 14.3.1 (14E300c)

clang --version
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
Target: x86_64-apple-darwin22.5.0
Thread model: posix

I tried all I could think of, but nothing solved. The same process did work for me two months ago (with a previous version of Cplex, and Gurobi) and worked flawlessly on three Ubuntus just a few hours back.

Any help would be appreciated, I'm stuck and I need OSI working.

    Thanks

    Antonio
[coinbrew log.txt](https://github.com/coin-or/coinbrew/files/12209767/coinbrew.log.txt)

**Comment by svigerske** [comment]
Probably due to some compiler update.
```
configure:23366: clang -o conftest -O3 -pipe -DNDEBUG -Wimplicit -Wparentheses -Wsequence-point -Wreturn-type -Wcast-qual -Wall -Wno-unknown-pragmas -Wno-long-long --no-warnings  -DOSI_BUILD   conftest.c -L/Users/frangio/Applications/CPLEX_Studio221/cplex/lib/x86-64_osx/static_pic/ -lcplex -lm  >&5
conftest.c:38:1: error: call to undeclared function 'CPXgetstat'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
CPXgetstat()
^
1 error generated.
```
Maybe add `--disable-cplex-libcheck`.

Setting environment variable `coin_skip_warn_cflags=yes` may also work, or adding `-Wno-implicit-function-declaration` to the compiler flags. I don't really understand why a warning results in an error.

**Comment by frangio68** [comment]
Thanks a lot, Stefan.

--disable-cplex-libcheck (and --disable-gurobi-libcheck for extra safety) did the trick, now it fully builds. Note that I tried with

--tests none

(first thing, in fact) that helped me previously, but not this time.

I guess clang becoming stricter on some obscure C feature (cf. "ISO C99 and later do not support implicit function declarations"?) could be the culprit. If you need help for testing a more stable solution, do not hesitate to ask. Meanwhile I'm closing the issue.

**Comment by tkralphs** [comment]
Thanks @frangio68, this is a known issue that is addressed by the new version of the BuildTools. Unfortunately, it's difficult to patch in the current release version that is still used by the most recent releases of Cbc and friends. I hope that there will soon be releases that use the newer build tools and that will address the issue.
